version: '3'

services:
  nodejs:
    build: .
    command: npm run serve
    restart: unless-stopped
    env_file: .env
    environment:
      - APP_PORT=$APP_PORT
    ports:
      - "${APP_PORT:-80}:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge